### ISSUE TITLE
Multi-GPU scenario

### ISSUE THREAD

**Issue by kannadaraj** [bricewalker/Hey-Jetson#2]
Hello @bricewalker ,

 thanks for sharing this. Very good work. Can this be  scaled to multigpu training?

**Comment by bricewalker** [comment]
Yes, Keras has built in support for (parallel) multi-gpu training with the Tensorflow backend. 

You will need to change the train_model function to convert the model to a multi_gpu_model(). The modified function should look something like this:


```
    model = add_ctc_loss(input_to_softmax)
    #
    parallel_model = multi_gpu_model(model, gpus=2)
    # Dummy lambda function for loss since CTC loss is implemented above
    parallel_model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=optimizer)
    # Make  initial results/ directory for saving model pickles
    if not os.path.exists('results'):
        os.makedirs('results')
    # Add callbacks
    checkpointer = ModelCheckpoint(filepath='results/'+save_model_path, verbose=0)
    terminator = callbacks.TerminateOnNaN()
    time_machiner = callbacks.History()
    logger = callbacks.CSVLogger('training.log')
    stopper = callbacks.EarlyStopping(monitor='val_loss', patience=2, verbose=1, mode='auto')
    reducer = callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=0, mode='auto', min_delta=0.0001, cooldown=0, min_lr=0)
    tensor_boarder = callbacks.TensorBoard(log_dir='./logs', batch_size=16,
                                          write_graph=True, write_grads=True, write_images=True,)
    # Fit/train model
    hist = parallel_model.fit_generator(generator=audio_gen.next_train(), steps_per_epoch=steps_per_epoch,
        epochs=epochs, validation_data=audio_gen.next_valid(), validation_steps=validation_steps,
        callbacks=[checkpointer, terminator, logger, time_machiner, tensor_boarder, stopper, reducer], verbose=verbose)
    # Save model loss
    with open('results/'+pickle_path, 'wb') as f:
        pickle.dump(hist.history, f)
 ```

Note: It looks like some have had difficulty with using multi_gpu_model() on models with lambda functions, [https://github.com/keras-team/keras/issues/10708)](https://github.com/keras-team/keras/issues/10708).

**Comment by kannadaraj** [comment]
Hi @bricewalker,

    Thanks a lot. This works like a charm. 

Also, this generated an attribute error in model.py for model.(attribute).. You may want to change that to model.module.(attribute)

**Comment by kannadaraj** [comment]
Hello @bricewalker 

Thanks for the code. It works like a charm. But it cannot save the model. Please can you suggest Why? Thanks in advance.

`Epoch 1/30
25/25 [==============================] - 509s 20s/step - loss: 351.3176 - val_loss: 1266.1460
Traceback (most recent call last):
  File "train_model_multigpu.py", line 660, in <module>
    spectrogram=True) # True for Spectrogram/False for MFCC
  File "train_model_multigpu.py", line 543, in train_model
    callbacks=[checkpointer, terminator, logger, time_machiner, tensor_boarder, stopper, reducer], verbose=verbose)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 247, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/callbacks.py", line 455, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/engine/network.py", line 1085, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/engine/saving.py", line 116, in save_model
    'config': model.get_config()
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/site-packages/keras/engine/network.py", line 926, in get_config
    return copy.deepcopy(config)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/anaconda3/envs/jetson_env/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects
`

**Comment by bricewalker** [comment]
Hi, this appears to be a problem introduced with your code changes: you stated in your message before you edited it that you changed model.(attribute) to model.module.(attribute) and I suggest you revisit that solution. It appears that you have converted the model into a module and are trying to save it, which python cannot do. A quick google or bing search of the error you are receiving shows many others have experienced your issue and shows some proposed solutions.

Error:
https://stackoverflow.com/questions/2790828/python-cant-pickle-module-objects-error

Examples of the error in multi-gpu Keras setups can be found here:
https://github.com/keras-team/keras/issues/8123
https://github.com/keras-team/keras/issues/8446

You can also check the Keras documentation at:
https://keras.io/

I have never worked with a multi-gpu device so I'm afraid I won't be able to provide any more troubleshooting, but please feel free to submit a pull request if you find a solution.
