### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by shriramhr** [bricewalker/Hey-Jetson#6]
Hi brice, 
I'm getting this error and I don't understand it at all. Some help would be much appreciated. I've installed all the dependencies and prepared the dataset etc... training starts too but getting this annoying error.

`2019-07-17 14:57:26.395650: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/training/Adam/gradients/bidirectional_7/while_1/strided_slice_3/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-07-17 14:57:26.396630: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/training/Adam/gradients/bidirectional_7/while_1/strided_slice_3/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-07-17 14:57:26.397577: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/training/Adam/gradients/bidirectional_7/while_1/strided_slice_3/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "train_model.py", line 842, in <module>
    spectrogram=True) # True for Spectrogram/False for MFCC
  File "train_model.py", line 536, in train_model
    callbacks=[checkpointer, terminator, logger, time_machiner, tensor_boarder], verbose=verbose)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/nvidia/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_3/training/Adam/gradients/bidirectional_7/while_1/strided_slice_3/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node training/Adam/gradients/bidirectional_7/while_1/strided_slice_3/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]
`

**Comment by shriramhr** [comment]
Fixed
